# YAML 项目配置文件

# 服务器配置
server:
  port: "8080"
  host: "localhost"
  
# 数据库配置
database:
  # 数据库类型 (sqlite)
  type: "sqlite"
  # 数据库文件名
  filename: "yaml.db"
  # 数据目录名 (相对于用户主目录)
  data_dir: ".yaml"
  # 数据保留天数
  retention_days: 30
  
# AI 服务配置
ai:
  # Gemini API 配置
  gemini:
    api_key: "sk-JIyFjsX1HIuusXty13315a05E29440D88369B8797159E3A4"
    base_url: "https://aihubmix.com/gemini"
    timeout_seconds: 120
    # 生成配置
    generation:
      temperature: 0.7
      max_output_tokens: 6717
      top_p: 0.8
      top_k: 40
      
# 监控配置
monitor:
  # 数据采集间隔 (秒)
  collection_interval: 0.01
  # 键盘输入缓冲区大小
  keyboard_buffer_size: 1000
  # 应用切换检测间隔 (毫秒)
  app_switch_interval: 500
  
# API 配置
api:
  # CORS 允许的源
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  # 默认查询限制
  default_limit: 50
  # 最大查询限制
  max_limit: 1000
  
# 日志配置
logging:
  # 日志级别 (debug, info, warn, error)
  level: "info"
  # 是否输出到文件
  file_output: false
  # 日志文件路径
  file_path: "logs/yaml.log"
  
# 前端配置
frontend:
  # Web 前端端口
  web_port: 3000
  # API 基础地址
  api_base_url: "http://localhost:8080/api/v1"